# Generated by Django 3.1.4 on 2021-01-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='management_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bridges.managementorganization', verbose_name='管理者'),
        ),
    ]
