# Generated by Django 3.1.5 on 2021-01-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_auto_20210111_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='management_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bridges', to='bridges.managementorganization', verbose_name='管理者'),
        ),
    ]
