# Generated by Django 3.1.5 on 2021-01-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0003_auto_20210111_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d/', verbose_name='メイン画像'),
        ),
    ]
