# Generated by Django 3.1.5 on 2021-01-23 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0004_bridge_image_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inspect', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='入力年月日')),
                ('bridge_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='bridges.bridge', verbose_name='橋梁名称')),
            ],
            options={
                'verbose_name_plural': '点検',
                'db_table': 'inspection',
            },
        ),
    ]
