# Generated by Django 3.1.5 on 2021-01-23 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0005_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='eval_bearing',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 支承部'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='所見'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_other',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 その他'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_overall',
            field=models.CharField(blank=True, max_length=10, verbose_name='橋梁毎の判定'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_substructure',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 下部構造'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_superstructure01',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 上部床版'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_superstructure02',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 上部横桁'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='eval_superstructure03',
            field=models.CharField(blank=True, max_length=10, verbose_name='判定 上部床版'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_inspect',
            field=models.DateField(default=datetime.datetime.now, verbose_name='点検年月日'),
        ),
    ]
