# Generated by Django 3.1.5 on 2021-01-26 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0006_auto_20210123_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_category', models.CharField(max_length=25, verbose_name='損傷の種類')),
                ('damege_category_cd', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='損傷の種類コード')),
                ('damage_rate', models.CharField(max_length=10, verbose_name='損傷程度')),
                ('damage_memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='所見')),
                ('bridge_component', models.CharField(blank=True, max_length=25, verbose_name='部材')),
                ('bridge_material', models.CharField(blank=True, max_length=25, verbose_name='材料')),
                ('bridge_member', models.CharField(blank=True, max_length=25, verbose_name='部位')),
                ('span_cd', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='スパン番号')),
                ('date_inspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bridges.inspection', verbose_name='点検年月日')),
            ],
            options={
                'verbose_name_plural': '損傷',
                'db_table': 'damage',
            },
        ),
    ]
