name: bridge app test
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DEBUG: 1
      SECRET_KEY: foo
      DATABASE: postgres
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd app
        pipenv install --dev --system
    - name: migration
      run: |
        cd app
        python manage.py migrate
    - name: run test
      run: |
        cd app
        python manage.py test    
